/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef centralNodeServiceV11_CONSTANTS_H
#define centralNodeServiceV11_CONSTANTS_H

#include "centralNodeServiceV11_types.h"

namespace HydraCN {

class centralNodeServiceV11Constants {
 public:
  centralNodeServiceV11Constants();

};

extern const centralNodeServiceV11Constants g_centralNodeServiceV11_constants;

} // namespace

#endif
