/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "centralNodeServiceV10_constants.h"

namespace HydraCN {

const centralNodeServiceV10Constants g_centralNodeServiceV10_constants;

centralNodeServiceV10Constants::centralNodeServiceV10Constants() {
}

} // namespace

