/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "centralNodeServiceV3_constants.h"

namespace HydraCN {

const centralNodeServiceV3Constants g_centralNodeServiceV3_constants;

centralNodeServiceV3Constants::centralNodeServiceV3Constants() {
}

} // namespace

