/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef centralNodeServiceV3_CONSTANTS_H
#define centralNodeServiceV3_CONSTANTS_H

#include "centralNodeServiceV3_types.h"

namespace HydraCN {

class centralNodeServiceV3Constants {
 public:
  centralNodeServiceV3Constants();

};

extern const centralNodeServiceV3Constants g_centralNodeServiceV3_constants;

} // namespace

#endif
