/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "centralnodeService_constants.h"

namespace HydraCN {

const centralnodeServiceConstants g_centralnodeService_constants;

centralnodeServiceConstants::centralnodeServiceConstants() {
}

} // namespace

