/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "centralNodeServiceV11_constants.h"

namespace HydraCN {

const centralNodeServiceV11Constants g_centralNodeServiceV11_constants;

centralNodeServiceV11Constants::centralNodeServiceV11Constants() {
}

} // namespace

