/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "centralNodeServiceV8_constants.h"

namespace HydraCN {

const centralNodeServiceV8Constants g_centralNodeServiceV8_constants;

centralNodeServiceV8Constants::centralNodeServiceV8Constants() {
}

} // namespace

