/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef centralnodeService_CONSTANTS_H
#define centralnodeService_CONSTANTS_H

#include "centralnodeService_types.h"

namespace HydraCN {

class centralnodeServiceConstants {
 public:
  centralnodeServiceConstants();

};

extern const centralnodeServiceConstants g_centralnodeService_constants;

} // namespace

#endif
