/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef centralNodeServiceV10_CONSTANTS_H
#define centralNodeServiceV10_CONSTANTS_H

#include "centralNodeServiceV10_types.h"

namespace HydraCN {

class centralNodeServiceV10Constants {
 public:
  centralNodeServiceV10Constants();

};

extern const centralNodeServiceV10Constants g_centralNodeServiceV10_constants;

} // namespace

#endif
