/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef centralNodeServiceV8_CONSTANTS_H
#define centralNodeServiceV8_CONSTANTS_H

#include "centralNodeServiceV8_types.h"

namespace HydraCN {

class centralNodeServiceV8Constants {
 public:
  centralNodeServiceV8Constants();

};

extern const centralNodeServiceV8Constants g_centralNodeServiceV8_constants;

} // namespace

#endif
