/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Process_constants.h"

namespace HydraWindows {

const ProcessConstants g_Process_constants;

ProcessConstants::ProcessConstants() {
}

} // namespace

