/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Process_CONSTANTS_H
#define Process_CONSTANTS_H

#include "Process_types.h"



class ProcessConstants {
 public:
  ProcessConstants();

};

extern const ProcessConstants g_Process_constants;



#endif
